### ISSUE TITLE
Check design goals (temporary)

### ISSUE THREAD

**Issue by karimosman** [svenvanhal/bachelorproject#36]

**Comment by karimosman** [comment]
I am adding comments if I think it should be different

**Comment by svenvanhal** [comment]
`Could we remove this part?  "and a little of our own as well in terms of bachelor project requirements". I personally do not like this, it sounds weird for me.` - Will remove it from the report, but still plays a role in determining the design goals and the scope of the project (not too small, not too big, difficult enough, our own experience etc.)

`I think that performance is more important that maintainability, for the user and for the developers actually. It is not really needed that it is maintainable, but if it slow no body will use it. Still both important, but from my point of view performance should be first or second, compatibility is as much as important as performance` - "It is not really needed that it is maintainable" is absolutely not the case from a business (and BEP) point of view. We haven't really discussed this with Key2Soft, but maintainability (code quality, documentation, testing) is an integral part of good software development. This of course shouldn't impact the performance too much (hence performance is also a major design goal), but since the module is already slow (runtime in the order of seconds or minutes), the impact of good maintainability (order of milliseconds) is negligible.

Timetable generation is always "slow", which is caused by an algorithm we have not designed an cannot change, so I believe that it's better to focus on maintainability and compatibility for our module. Performance is still important, but not the most (because we can't achieve that).

`Maybe say that is important from the developers point in stead of business?` - Business point of view == developers point of view (or Key2Soft in general). In the introduction I make a distinction between user and business needs and this is clearly a business need. Can rename it to "client" in the report to make that more clear?

`maybe add documentation?` - How would you translate that into a design goal? Can we change the way we develop or focus on different things to make the module more documentable? Maybe make this a part of `Code Quality` (as it is an important factor to consider)
